# Generated by Django 6.0.3 on 2026-03-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_customer_account_customer_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
