# Generated by Django 6.0.3 on 2026-03-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_customer_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email_address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
